### ISSUE TITLE
Big list

### ISSUE THREAD

**Issue by koshinf** [koshinf/Bloodborne_Lore#2]
- [x] Invite members

- [x] Check your notifications

- [x] Make folders for repo

- [x] Finish repo set up

**Comment by koshinf** [comment]
Comment that you have checked to make sure you have all three repos;
 **DH, personal, and obviously this one.**

You can find out easily by just going to the github home page to see what repos you are apart of.

Also feel free to add to your comment what folders you think we should have that are not already made.

**Comment by NADGIT** [comment]
I have all three repos
